/* Datos del sitio: habitaciones, galería, itinerario y textos en inglés */
window.EST = {
  phone: '573208039667',

  slides: [
    { src: 'img/hero-fachada.webp', es: 'La casa', en: 'The house', alt: 'Fachada de la casa campesina con balcones de madera y jardín' },
    { src: 'img/hero-aerea.webp', es: 'Frente al pueblo', en: 'Facing the town', alt: 'Vista aérea del hotel con el pueblo de San Agustín en la montaña' },
    { src: 'img/hero-jardin.webp', es: 'El jardín', en: 'The garden', alt: 'Jardín con sombrilla roja, setos y la casa al fondo' },
    { src: 'img/hero-noche.webp', es: 'De noche', en: 'At night', alt: 'La casa iluminada de noche' }
  ],

  rooms: {
    r1: { cat: ['pareja'], rate: null, size: 31,
      es: { name: 'Habitación Superior', tag: 'Para parejas', beds: '1 cama doble', view: 'Jardín y montaña',
        desc: 'Una habitación tranquila con cama doble, zona de estar y ventana al jardín. Buena para una pareja que quiere salir temprano al parque.',
        amen: ['Baño privado con ducha', 'TV de pantalla plana', 'Zona de estar', 'Secador de pelo', 'Artículos de aseo', 'WiFi gratis'] },
      en: { name: 'Superior Room', tag: 'For couples', beds: '1 double bed', view: 'Garden and mountains',
        desc: 'A quiet room with a double bed, a seating area and a window onto the garden. Good for a couple heading out early to the park.',
        amen: ['Private bathroom with shower', 'Flat-screen TV', 'Seating area', 'Hairdryer', 'Toiletries', 'Free WiFi'] },
      photos: ['386644173', '584122288', '584123276', '386644328'] },
    r2: { cat: ['pareja', 'familia'], rate: 225000, size: 35,
      es: { name: 'Doble Superior', tag: 'Amigos o parejas', beds: '2 camas dobles', view: 'Montaña',
        desc: 'Dos camas dobles, techo de vigas y ventanas de madera abiertas a la montaña. Sirve para amigos, o para una pareja que viaja con un hijo.',
        amen: ['Baño privado con ducha', 'TV de pantalla plana', 'Vista a la montaña', 'Toallas y ropa de cama', 'Artículos de aseo', 'WiFi gratis'] },
      en: { name: 'Superior Double', tag: 'Friends or couples', beds: '2 double beds', view: 'Mountains',
        desc: 'Two double beds, a beamed ceiling and wooden windows open to the mountains. Works for friends, or a couple travelling with a child.',
        amen: ['Private bathroom with shower', 'Flat-screen TV', 'Mountain view', 'Towels and bed linen', 'Toiletries', 'Free WiFi'] },
      photos: ['103798445', '103798447', '390618050', '103798414'] },
    r3: { cat: ['pareja', 'especial'], rate: 295000, size: 23,
      es: { name: 'Suite vista al jardín', tag: 'Cabaña con chimenea', beds: '1 cama extragrande', view: 'Jardín',
        desc: 'Una cabaña aparte, rodeada de jardín, con chimenea de piedra y un columpio de madera junto a la cama. La más romántica de la casa.',
        amen: ['Chimenea de piedra', 'Columpio de madera', 'Minibar', 'Baño privado', 'TV de pantalla plana', 'WiFi gratis'] },
      en: { name: 'Garden-view Suite', tag: 'Cabin with fireplace', beds: '1 king bed', view: 'Garden',
        desc: 'A separate cabin surrounded by garden, with a stone fireplace and a wooden swing chair next to the bed. The most romantic room in the house.',
        amen: ['Stone fireplace', 'Wooden swing chair', 'Minibar', 'Private bathroom', 'Flat-screen TV', 'Free WiFi'] },
      photos: ['120756891', '120756883', '120756899', '390617702', '386641870'] },
    r4: { cat: ['pareja', 'especial'], rate: 320000, size: 38,
      es: { name: 'Suite con balcón', tag: 'Con balcón', beds: '1 cama extragrande', view: 'Jardín y montaña',
        desc: 'La habitación más amplia, con cama extragrande y salida a un balcón de madera sobre el jardín. Para desayunar mirando la montaña.',
        amen: ['Balcón y terraza', 'Vista al jardín y la montaña', 'Baño privado', 'TV de pantalla plana', 'Artículos de aseo', 'WiFi gratis'] },
      en: { name: 'Suite with balcony', tag: 'With balcony', beds: '1 king bed', view: 'Garden and mountains',
        desc: 'The largest room, with a king bed and a wooden balcony over the garden. For breakfast with a view of the mountains.',
        amen: ['Balcony and terrace', 'Garden and mountain view', 'Private bathroom', 'Flat-screen TV', 'Toiletries', 'Free WiFi'] },
      photos: ['106803890', '103798457', '103798389', '386644859', '326041110'] },
    r5: { cat: ['familia'], rate: 275000, size: 35,
      es: { name: 'Triple Superior', tag: 'Familias', beds: '2 sencillas + 1 doble', view: 'Jardín',
        desc: 'Tres camas bajo un techo de vigas, con ventanas al jardín. Espacio de sobra para una familia con niños.',
        amen: ['Baño privado con ducha', 'TV de pantalla plana', 'Vista al jardín', 'Toallas y ropa de cama', 'Artículos de aseo', 'WiFi gratis'] },
      en: { name: 'Superior Triple', tag: 'Families', beds: '2 singles + 1 double', view: 'Garden',
        desc: 'Three beds under a beamed ceiling, with windows onto the garden. Plenty of room for a family with kids.',
        amen: ['Private bathroom with shower', 'Flat-screen TV', 'Garden view', 'Towels and bed linen', 'Toiletries', 'Free WiFi'] },
      photos: ['103798429', '103798439'] },
    r6: { cat: ['familia'], rate: 320000, size: 35,
      es: { name: 'Cuádruple Superior', tag: 'Familias y grupos', beds: '1 sencilla + 2 dobles', view: 'Jardín y montaña',
        desc: 'Tres camas, dos de ellas dobles, en una habitación amplia con ventanas hacia los árboles. Para familias grandes o grupos.',
        amen: ['Baño privado con ducha', 'TV de pantalla plana', 'Vista al jardín y la montaña', 'Toallas y ropa de cama', 'Artículos de aseo', 'WiFi gratis'] },
      en: { name: 'Superior Quadruple', tag: 'Families and groups', beds: '1 single + 2 doubles', view: 'Garden and mountains',
        desc: 'Three beds, two of them doubles, in a spacious room with windows onto the trees. For larger families or groups.',
        amen: ['Private bathroom with shower', 'Flat-screen TV', 'Garden and mountain view', 'Towels and bed linen', 'Toiletries', 'Free WiFi'] },
      photos: ['103798439', '103798429'] }
  },

  gallery: [
    ['386642401', 'La fachada', 'The façade'],
    ['103798421', 'El corredor de las hamacas', 'The hammock veranda'],
    ['386644859', 'Los balcones', 'The balconies'],
    ['459952018', 'La fogata', 'The fire pit'],
    ['103798405', 'El comedor', 'The dining room'],
    ['103798399', 'La casa de noche', 'The house at night'],
    ['386642143', 'El jardín', 'The garden'],
    ['386642571', 'La cabaña de la suite', 'The suite cabin'],
    ['103798375', 'La recepción', 'Reception'],
    ['103798392', 'La sala', 'The lounge'],
    ['103798433', 'El restaurante', 'The restaurant'],
    ['103798470', 'El desayuno', 'Breakfast'],
    ['386642466', 'Palmas y flores', 'Palms and flowers'],
    ['103798463', 'La casa entre flores', 'The house among flowers'],
    ['386641981', 'Dos pisos de madera', 'Two wooden storeys'],
    ['459952181', 'La zona de juegos', 'The playground'],
    ['103798369', 'El corredor', 'The veranda'],
    ['386642600', 'Con el pueblo al fondo', 'With the town behind'],
    ['386642651', 'Vista aérea', 'Aerial view'],
    ['243224843', 'La finca completa', 'The whole property'],
    ['106688584', 'La entrada', 'The entrance']
  ],

  itin: {
    1: [
      { day: 1, t: 'am', es: ['Parque Arqueológico', 'Sal caminando después del desayuno. Recorre las mesitas, la Fuente de Lavapatas y el Bosque de las Estatuas.', 'A pie · 15 min'],
        en: ['Archaeological Park', 'Walk over after breakfast. See the burial mounds, the Lavapatas Fountain and the Forest of Statues.', 'On foot · 15 min'] },
      { day: 1, t: 'pm', es: ['La Chaquira a caballo', 'Cabalgata por las veredas hasta el mirador sobre el cañón del Magdalena.', 'A caballo · medio día'],
        en: ['La Chaquira on horseback', 'Ride along country lanes to the viewpoint over the Magdalena canyon.', 'On horseback · half day'] },
      { day: 1, t: 'ev', es: ['Cena en el pueblo', 'Baja caminando al centro de San Agustín y vuelve a descansar en la casa.', 'A pie · 10 min'],
        en: ['Dinner in town', 'Walk down to the centre of San Agustín and come back to rest at the house.', 'On foot · 10 min'] }
    ],
    2: [
      { day: 2, t: 'am', es: ['Alto de los Ídolos y Alto de las Piedras', 'En Isnos están las estatuas más grandes de la cultura agustiniana.', 'En carro · día completo'],
        en: ['Alto de los Ídolos and Alto de las Piedras', 'Isnos holds the largest statues of the San Agustín culture.', 'By car · full day'] },
      { day: 2, t: 'pm', es: ['Salto de Bordones', 'Una de las cascadas más altas de Colombia, de camino de regreso desde Isnos.', 'En carro'],
        en: ['Bordones Falls', 'One of the tallest waterfalls in Colombia, on the way back from Isnos.', 'By car'] },
      { day: 2, t: 'ev', es: ['Fogata en el jardín', 'Cierra el día alrededor del fuego, en el círculo de piedra del hotel.', 'En el hotel'],
        en: ['Fire pit in the garden', 'End the day around the fire in the hotel’s stone circle.', 'At the hotel'] }
    ],
    3: [
      { day: 3, t: 'am', es: ['Estrecho del Magdalena', 'El río más largo de Colombia pasando entre rocas en su punto más angosto.', 'En carro · medio día'],
        en: ['Magdalena Strait', 'Colombia’s longest river squeezing between rocks at its narrowest point.', 'By car · half day'] },
      { day: 3, t: 'pm', es: ['La Pelota y El Purutal', 'Estatuas que todavía conservan su color, a pocos kilómetros de la casa.', 'A caballo o en carro'],
        en: ['La Pelota and El Purutal', 'Statues that still keep their colour, a few kilometres from the house.', 'On horseback or by car'] },
      { day: 3, t: 'ev', es: ['Última noche en la casa', 'Hamaca en el corredor y descanso antes de seguir el viaje.', 'En el hotel'],
        en: ['Last night at the house', 'A hammock on the veranda and a rest before moving on.', 'At the hotel'] }
    ]
  },

  t: {
    es: {
      tbd: 'Por definir', none: 'Nada por ahora', pick: 'Elegir', addDates: 'Agregar fechas',
      hi: 'Hola', im: ', soy ', intro: '. Quiero reservar en Estorake:', dates: 'Fechas', from: ' al ', ppl: 'Huéspedes', room: 'Habitación', add: 'Agregar',
      close: '¿Me confirman disponibilidad y tarifa?', dQ: 'Hola, ¿tienen disponibilidad en Estorake?', dAny: 'Que me recomienden',
      adults: function (n) { return n === 1 ? '1 adulto' : n + ' adultos'; }, kids: function (n) { return n === 1 ? '1 niño' : n + ' niños'; },
      nights: function (n) { return n === 1 ? '1 noche' : n + ' noches'; },
      need: 'Elige la fecha de llegada y la de salida.', needOut: 'Ahora elige la fecha de salida.',
      selIn: 'Elige tu llegada', selOut: 'Ahora elige tu salida', clear: 'Borrar', done: 'Listo',
      prevM: 'Mes anterior', nextM: 'Mes siguiente',
      copied: 'Dirección copiada', copyFail: 'No se pudo copiar. Selecciona el texto manualmente.', linkCopied: 'Enlace copiado.',
      shareText: 'Mira este hotel campestre en San Agustín, a pie del Parque Arqueológico.',
      wa: 'Hola, quiero información sobre el Hotel Estorake.', wa_tour: 'Hola, quiero información sobre los tours en San Agustín.',
      from_night: 'Desde, por noche', rate: 'Tarifa', byDates: 'Según fechas', estFor: function (n) { return 'Estimado para ' + (n === 1 ? '1 noche' : n + ' noches'); },
      estHint: 'Elige fechas para ver un estimado', estNote: 'Valor de referencia; se confirma por WhatsApp.',
      bookThis: 'Reservar esta habitación', beds: 'Camas', size: 'Tamaño', view: 'Vista', photos: 'fotos',
      itinSum: function (d) { return d === 1 ? 'Un día bien aprovechado, sin carro.' : d === 2 ? 'Lo esencial de San Agustín e Isnos.' : 'El recorrido completo, con tiempo para descansar.'; },
      day: 'Día', am: 'Mañana', pm: 'Tarde', ev: 'Noche',
      itinWa: function (d) { return 'Hola, quiero armar un plan de ' + d + (d === 1 ? ' día' : ' días') + ' en San Agustín con Estorake:'; },
      itinClose: '¿Me ayudan con guías y disponibilidad?',
      wxNow: 'Ahora en San Agustín', loc: 'es-CO',
      wx: { 0: 'Despejado', 1: 'Casi despejado', 2: 'Parcialmente nublado', 3: 'Nublado', 45: 'Neblina', 48: 'Neblina', 51: 'Llovizna', 53: 'Llovizna', 55: 'Llovizna', 61: 'Lluvia suave', 63: 'Lluvia', 65: 'Lluvia fuerte', 80: 'Chubascos', 81: 'Chubascos', 82: 'Chubascos fuertes', 95: 'Tormenta' }
    },
    en: {
      tbd: 'Not set yet', none: 'Nothing yet', pick: 'Choose', addDates: 'Add dates',
      hi: 'Hi', im: ', I’m ', intro: '. I’d like to book at Estorake:', dates: 'Dates', from: ' to ', ppl: 'Guests', room: 'Room', add: 'Add-ons',
      close: 'Could you confirm availability and rates?', dQ: 'Hi, do you have availability at Estorake?', dAny: 'Recommend one for me',
      adults: function (n) { return n === 1 ? '1 adult' : n + ' adults'; }, kids: function (n) { return n === 1 ? '1 child' : n + ' children'; },
      nights: function (n) { return n === 1 ? '1 night' : n + ' nights'; },
      need: 'Choose your arrival and departure dates.', needOut: 'Now choose your departure date.',
      selIn: 'Choose your arrival', selOut: 'Now choose your departure', clear: 'Clear', done: 'Done',
      prevM: 'Previous month', nextM: 'Next month',
      copied: 'Address copied', copyFail: 'Couldn’t copy. Please select the text manually.', linkCopied: 'Link copied.',
      shareText: 'Check out this country hotel in San Agustín, walking distance from the Archaeological Park.',
      wa: 'Hi, I’d like information about Hotel Estorake.', wa_tour: 'Hi, I’d like information about tours in San Agustín.',
      from_night: 'From, per night', rate: 'Rate', byDates: 'Depends on dates', estFor: function (n) { return 'Estimate for ' + (n === 1 ? '1 night' : n + ' nights'); },
      estHint: 'Choose dates to see an estimate', estNote: 'Reference price; confirmed on WhatsApp.',
      bookThis: 'Book this room', beds: 'Beds', size: 'Size', view: 'View', photos: 'photos',
      itinSum: function (d) { return d === 1 ? 'One well-used day, no car needed.' : d === 2 ? 'The essentials of San Agustín and Isnos.' : 'The full route, with time to rest.'; },
      day: 'Day', am: 'Morning', pm: 'Afternoon', ev: 'Evening',
      itinWa: function (d) { return 'Hi, I’d like to plan ' + d + (d === 1 ? ' day' : ' days') + ' in San Agustín with Estorake:'; },
      itinClose: 'Could you help with guides and availability?',
      wxNow: 'Now in San Agustín', loc: 'en-US',
      wx: { 0: 'Clear', 1: 'Mostly clear', 2: 'Partly cloudy', 3: 'Cloudy', 45: 'Fog', 48: 'Fog', 51: 'Drizzle', 53: 'Drizzle', 55: 'Drizzle', 61: 'Light rain', 63: 'Rain', 65: 'Heavy rain', 80: 'Showers', 81: 'Showers', 82: 'Heavy showers', 95: 'Thunderstorm' }
    }
  }
};
